To Do List - Day 3: Interactive list
hajnaloltyan/todo-list pull request #5
Opened 2023-06-07 15:49 UTC by hajnaloltyan

To Do List - Day 3: Interactive List

* Add completed checkbox functionality to mark tasks 'done'

* Store in LocalStorage the updated todos array

* Preserve completed todo's checkmark after page refresh

* Add Clear All Button to remove completed tasks and update indexes of remaining todos

* [Live Demo](https://hajnaloltyan.github.io/todo-list/)

**Site was deployed by adding scripts to use gh-pages**

2023-06-07 16:44 UTC, Gambit142 requested changes
Hi @hajnaloltyan 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- There is a function for updating the status of a task ✔️ 
- There is a function for clearing all completed tasks ✔️ 
- Use the `Array.filter` method ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-07 16:44 UTC, Gambit142 commented on src/handleTodos.js
> +  }
- [ ] One of the project requirements is to put the function that updates the completed status of a task and the function that clears all completed tasks in a new module. Using the module structure makes it easier to maintain a code base. Kindly implement this change. 👍 😎

2023-06-07 21:26 UTC, Gambit142 commented on src/handleTodos.js
> +  }
Hi @hajnaloltyan, please find the project requirements highlighted below:

![Screenshot_1](https://github.com/hajnaloltyan/todo-list/assets/77106962/146481d2-928d-49c3-9d01-4225eec08d89)

2023-06-07 21:42 UTC, bimbolabuari reviewed
Hello @hajnaloltyan  👋,

_This is an additional review as a result of the second opinion request._

- Kudos on working on this milestone 👍 
  - As part of the project requirement, we are asked to create a new JS file and import as a module, it is possible to work with classes and modules check this [MDN article on classes and modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#modules_and_classes).

Keep rocking 🚀!

2023-06-08 21:53 UTC, AdnanOlarmmi requested changes
Hi @hajnaloltyan, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice app.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 21:53 UTC, AdnanOlarmmi commented on src/handleTodos.js
> +  }
> * [ ]  One of the project requirements is to put the function that updates the completed status of a task and the function that clears all completed tasks in a new module. Using the module structure makes it easier to maintain a code base. Kindly implement this change. 👍 😎

- [ ] Hi @hajnaloltyan, hope you're doing well. Nice seeing you making progress in the program, kindly adhere to the previous reviewer's suggestion, since this has also been suggested by a senior code reviewer it is then mandatory. Have a nice time.

2023-06-09 00:07 UTC, Zuhaib042 approved these changes
Hi @hajnaloltyan 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)
## Highlights
✅ Descriptive PR
✅ Implemented suggested changes
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 00:08 UTC, merged